### ISSUE TITLE
Values for CpuUsage crossing 100

### ISSUE THREAD

**Issue by archit2508** [souch/AndroidCPU#1]
Hello,

I am trying to use CpuInfo.java class to fetch CPU usage.

While the class says that method getCpuUsage() will always return values between 0-100, I am receiving values >100 like 150, 270, 300, 1247 etc. only in cases when I am using my device heavily.
Expectation was to receive values ~100 during heavy usage.

Requesting you to correct this issue.

**Comment by souch** [comment]
Hi, i 'am in holiday right now. So don't expect quick fix.
How many core or what is your device ?
What is your android version ?

**Comment by archit2508** [comment]
Hello,
Thanks for your response.
My device is a POS android device - Nexgo N3.
It is a quad-core device with lollipop version.

**Comment by souch** [comment]
Can you post your code that call getCpuUsage() ?
Note that getCpuUsage calls must be separated by enough time to be consistent (at least some ms).

**Comment by archit2508** [comment]
I am just calling getCpuUsage() function on an interval of around 15-20 mins

**Comment by souch** [comment]
1e328b4d3d2b577499b781e8726c3e9cf2d0e767 must fix that
