### ISSUE TITLE
Error: java.io.FileNotFoundException: /proc/stat: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by helloo0-0oworld** [souch/AndroidCPU#2]
Hi. I have problem when getCPUUsage
java.io.FileNotFoundException: /proc/stat: open failed: EACCES (Permission denied)
W/System.err(11158): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11158): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
W/System.err(11158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
W/System.err(11158): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(11158): 	at libcore.io.Linux.open(Native Method)

**Comment by souch** [comment]
It seems /proc/stat is no longer accessible since android 8.0. I will investigate that.

**Comment by souch** [comment]
Yep, /proc/stat is no longer accessible since android 8.0 (https://stackoverflow.com/questions/46182041/get-cpu-usage-of-a-device-running-android-8-oreo) and nothing practical has been propose instead by Android (Android must be rooted or app must be a system app).

**Comment by souch** [comment]
I will propose a fallback for > oreo, guessing cpu usage by looking at the cpu frequency. I don't know if cpu frequency is very meaningful or precise, but should be precise for at least full speed and idle state.

**Comment by souch** [comment]
last commit 49a8a9c propose a fallback on cpufreq.
